Avoid accessing QListWidget's model directly
Seems to cause the following error on Mac:

```
RuntimeError: no access to protected functions or signals for objects not created from Python
```